[meta_properties]
	id = "b7ca18d296aab7d5"
	asset_kind = "L10n"

[asset_properties]
    # since english is what the game's source is already in, it has no `translation`
    # or `src_cache` property.
	[asset_properties.languages.eng]
		display_name = "English"
		ship = true
		default_pronoun = "they_them"
		date_order = "DayFirst"
		infusion_order = "Adjective"
        infusion_space = " "
		automatic_linebreaks = true
        commas_in_numbers = true
        common_button_height = 19
		pronoun_display_order = [
			"they_them",
			"she_her",
			"he_him",
			"she_they",
			"they_she",
			"he_they",
			"they_he",
			"he_she",
			"she_he",
			"it_its",
			"all",
			"none",
		]
		[asset_properties.languages.eng.pronouns]
			they_them = { display = "They/Them", macros = ["they"] }
			she_her = { display = "She/Her", macros = ["she"] }
			he_him = { display = "He/Him", macros = ["he"] }
			she_they = { display = "She/They", macros = ["she", "they"] }
			they_she = { display = "They/She", macros = ["they", "she"] }
			he_they = { display = "He/They", macros = ["he", "they"] }
			they_he = { display = "They/He", macros = ["they", "he"] }
			he_she = { display = "He/She", macros = ["he", "she"] }
			she_he = { display = "She/He", macros = ["she", "he"] }
			it_its = { display = "It/Its", macros = ["it"] }
			all = { display = "All", macros = ["they", "he", "she", "it"] }
			none = { display = "None", macros = ["none"] }

	[asset_properties.languages.jpn]
	    translation = "d6bc86444003cd92"
		src_cache = "cfc938aab21b0987"
		display_name = "日本語"
		ship = false
		default_pronoun = "they_them"
		date_order = "YearFirst"
		infusion_order = "Adjective"
        infusion_space = ""
		automatic_linebreaks = false
		text_input_character_limit = 6
        commas_in_numbers = true
        common_button_height = 20
		pronoun_display_order = [
			"they_them",
			"she_her",
			"he_him",
			"she_they",
			"they_she",
			"he_they",
			"they_he",
			"he_she",
			"she_he",
			"it_its",
			"all",
			"none",
		]
		[asset_properties.languages.jpn.pronouns]
			they_them = { display = "わたし", macros = ["they"] }
			she_her = { display = "あたし", macros = ["she"] }
			he_him = { display = "おれ", macros = ["he"] }
			she_they = { display = "うち", macros = ["she", "they"] }
			they_she = { display = "あたい", macros = ["they", "she"] }
			he_they = { display = "おいら", macros = ["he", "they"] }
			they_he = { display = "おれっち", macros = ["they", "he"] }
			he_she = { display = "わい", macros = ["he", "she"] }
			she_he = { display = "ぼく", macros = ["she", "he"] }
			it_its = { display = "当方", macros = ["it"] }
			all = { display = "自分", macros = ["they", "he", "she", "it"] }
			none = { display = "われ", macros = ["none"] }

	[asset_properties.languages.zh-Hans]
		display_name = "简体中文"
        translation = "e5d03134f9aeeab3"
        src_cache = "f1f0fbfda5d1c923"
		ship = false
		default_pronoun = "they_them"
		automatic_linebreaks = true
		date_order = "DayFirst"
		infusion_order = "Adjective"
        infusion_space = " "
        commas_in_numbers = true
        common_button_height = 20
		pronoun_display_order = [
			"they_them",
			"she_her",
			"he_him",
			"she_they",
			"they_she",
			"he_they",
			"they_he",
			"he_she",
			"she_he",
			"it_its",
			"all",
			"none",
		]
		[asset_properties.languages.zh-Hans.pronouns]
			they_them = { display = "TA/TA", macros = ["they"] }
			she_her = { display = "她/她", macros = ["she"] }
			he_him = { display = "他/他", macros = ["he"] }
			she_they = { display = "她/TA", macros = ["she", "they"] }
			they_she = { display = "TA/她", macros = ["they", "she"] }
			he_they = { display = "他/TA", macros = ["he", "they"] }
			they_he = { display = "TA/他", macros = ["they", "he"] }
			he_she = { display = "他/她", macros = ["he", "she"] }
			she_he = { display = "她/他", macros = ["she", "he"] }
			it_its = { display = "它/它", macros = ["it"] }
			all = { display = "任意", macros = ["they", "he", "she", "it"] }
			none = { display = "无", macros = ["none"] }

	[asset_properties.languages.zh-Hant]
		display_name = "繁體中文"
		translation = "f6d6fce844da27"
        src_cache = "4e070edb17ce8246"
		ship = false
		default_pronoun = "they_them"
		automatic_linebreaks = true
		date_order = "DayFirst"
		infusion_order = "Adjective"
        infusion_space = " "
        commas_in_numbers = true
        common_button_height = 20
		pronoun_display_order = [
			"they_them",
			"she_her",
			"he_him",
			"she_they",
			"they_she",
			"he_they",
			"they_he",
			"he_she",
			"she_he",
			"it_its",
			"all",
			"none",
		]
		[asset_properties.languages.zh-Hant.pronouns]
			they_them = { display = "TA/TA", macros = ["they"] }
			she_her = { display = "她/她", macros = ["she"] }
			he_him = { display = "他/他", macros = ["he"] }
			she_they = { display = "她/TA", macros = ["she", "they"] }
			they_she = { display = "TA/她", macros = ["they", "she"] }
			he_they = { display = "他/TA", macros = ["he", "they"] }
			they_he = { display = "TA/他", macros = ["they", "he"] }
			he_she = { display = "他/她", macros = ["he", "she"] }
			she_he = { display = "她/他", macros = ["she", "he"] }
			it_its = { display = "它/它", macros = ["it"] }
			all = { display = "任意", macros = ["they", "he", "she", "it"] }
			none = { display = "無", macros = ["none"] }

	[asset_properties.languages.spa]
        translation = "708f96b0a3e4fa9b"
        src_cache = "b774daf97866becf"
		display_name = "Español"
		ship = false
		default_pronoun = "elle"
		automatic_linebreaks = true
		date_order = "DayFirst"
		infusion_order = "Adjective"
        infusion_space = " "
        commas_in_numbers = false
        common_button_height = 19
		pronoun_display_order = ["elle", "ella", "el"]

		[asset_properties.languages.spa.pronouns]
			elle = { display = "Elu/Delu", macros = ["they"] }
			ella = { display = "Ela/Dela", macros = ["she"] }
			el = { display = "Ele/Dele", macros = ["he"] }

	[asset_properties.languages.fra]
		display_name = "Français"
		translation = "99631018078c5c8e"
        src_cache = "627ae18df618b154"
		ship = false
		default_pronoun = "they_them"
		automatic_linebreaks = true
		date_order = "DayFirst"
		infusion_order = "Adjective"
        infusion_space = " "
        commas_in_numbers = true
        common_button_height = 19
		pronoun_display_order = ["they_them", "she_her", "he_him"]

		[asset_properties.languages.fra.pronouns]
			they_them = { display = "Iel/Iel", macros = ["they"] }
			she_her = { display = "Elle/Elle", macros = ["she"] }
			he_him = { display = "Il/Lui", macros = ["he"] }

	[asset_properties.languages.kor]
		display_name = "한국어"
		translation = "6485d540921c3680"
        src_cache = "8893cbcca635cf2d"
		ship = false
		automatic_linebreaks = true
		default_pronoun = "they_them"
		date_order = "DayFirst"
		infusion_order = "Adjective"
        infusion_space = " "
        commas_in_numbers = true
        common_button_height = 19
		pronoun_display_order = [
			"they_them",
			"she_her",
			"he_him",
			"she_they",
			"they_she",
			"he_they",
			"they_he",
			"he_she",
			"she_he",
			"it_its",
			"all",
			"none",
		]
		[asset_properties.languages.kor.pronouns]
			they_them = { display = "그 사람/그 사람", macros = ["they"] }
			she_her = { display = "그녀/그녀", macros = ["she"] }
			he_him = { display = "그/그", macros = ["he"] }
			she_they = { display = "그녀/그 사람", macros = ["she", "they"] }
			they_she = { display = "그 사람/그녀", macros = ["they", "she"] }
			he_they = { display = "그/그 사람", macros = ["he", "they"] }
			they_he = { display = "그 사람/그", macros = ["they", "he"] }
			he_she = { display = "그/그녀", macros = ["he", "she"] }
			she_he = { display = "그녀/그", macros = ["she", "he"] }
			it_its = { display = "그 사람", macros = ["it"] }
			all = { display = "전부", macros = ["they", "he", "she", "it"] }
			none = { display = "없음", macros = ["none"] }

	[asset_properties.languages.rus]
		display_name = "Русский"
		translation = "5e9fdb7035a7148f"
        src_cache = "6c3f7853ef488d24"
		ship = false
		default_pronoun = "they_them"
		automatic_linebreaks = true
		date_order = "DayFirst"
		infusion_order = "Noun"
        infusion_space = " "
		pronoun_display_order = ["they_them", "she_her", "he_him", "it_its", "all"]
        commas_in_numbers = true
        common_button_height = 19
		[asset_properties.languages.rus.pronouns]
			they_them = { display = "Они / Их", macros = ["p"] }
			she_her = { display = "Она / Её", macros = ["f"] }
			he_him = { display = "Он / Его", macros = ["m"] }
			it_its = { display = "Оно / Их", macros = ["n"] }
			all = { display = "Любые", macros = ["p", "m", "f", "n"] }

	# all of these paths have some localization data, so we'll try to find
	# what localization we have and replace what's here with what's in `translations`.
	[asset_properties.fiddle_renames]
		misc_local = ["*"]
		"items/" = ["*/name", "*/description"]
		"museum_wings/" = ["name", "sets/*/name", "sets/*/description"]
		"npcs/" = ["name", "job"]
		"object_prototypes/building" = ["*/name"]
		"quests/" = [
			"*/name",
			"*/description",
			"*/stages/*/objective_description",
			"*/stages/*/turn_in_description",
			"*/stages/*/turn_in_button_label",
		]
		"quests/crown_registry" = ["tag_registrations/*/text"]
		"ranching/animals/" = [
			"core/name",
			"core/plural_name",
			"core/female_other",
			"core/male_other",
			"core/new_baby_born",
			"variants/*/name",
			"cosmetics/*/name",
		]
		"ui/crafting/" = ["categories/*/name", "categories/*/sub_categories/*/name"]
		"ui/character_customization" = ["*/*/name"]
		"ui/skill_menu/" = ["name"]
		"ui/tutorials" = ["*/title", "*/steps/*/text"]
		festivals = ["*/name"]
		letters = ["*/local", "*/subject_line"]
		locations = ["*/name"]
		misc = ["inn/soup_kinds/*"]
		perks = ["*/name", "*/description"]
		renown = ["ranks/*/name"]
		player_assets = ["*/name"]
		stores = ["*/name"]
		infusions = ["*/name", "*/description"]
		"dungeons/dungeons" = ["biomes/*/name"]
		spells = ["*/name", "*/description", "*/type"]
		pets = ["cosmetic_sets/*/name", "variants/*/name"]
		dates = ["*/name", "*/description", "*/photo_title"]
		children = ["*/name"]
		cameos = ["name"]
        songs = ["*/name"]
        bell_sounds = ["*/name"]
